
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 14;
  public static final int INT = 13;
  public static final int DOSP = 12;
  public static final int PC = 10;
  public static final int PA = 9;
  public static final int PROG = 2;
  public static final int EOF = 0;
  public static final int PYC = 11;
  public static final int PROC = 3;
  public static final int NUMERO = 7;
  public static final int ASIG = 8;
  public static final int ID = 6;
  public static final int error = 1;
  public static final int ERRORLEX = 15;
  public static final int END = 4;
  public static final int BEGIN = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROG",
  "PROC",
  "END",
  "BEGIN",
  "ID",
  "NUMERO",
  "ASIG",
  "PA",
  "PC",
  "PYC",
  "DOSP",
  "INT",
  "COMA",
  "ERRORLEX"
  };
}

