/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Analizador.Lexer;
import Analizador.parser;
import Interprete.Instruccion;
import Interprete.Llamada;
import Interprete.Metodo;
import Interprete.Programa;
import java.io.StringReader;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author willi
 */
public class Principal extends javax.swing.JFrame {

    public static final String PRUEBA = "programa NOMBRE\n"
            + "\n"
            + "\tprocedimiento NOMBRE (param)\n"
            + "\t\tNOMBRE2();\n"
            + "\n"
            + "\t\n"
            + "\tend\n"
            + "\n"
            + "\tprocedimiento NOMBRE2 (param)\n"
            + "\t\tNOMBRE3();\n"
            + "\t\tNOMBRE();\n"
            + "\n"
            + "\tend\n"
            + "\n"
            + "\tprocedimiento NOMBRE3 (param)\n"
            + "\t\tNOMBRE(3);\n"
            + "\n"
            + "\tend\n"
            + "\n"
            + "begin\n"
            + "\n"
            + "\tx : integer;\n"
            + "\ty : integer;\n"
            + "\t\n"
            + "\tx := NOMBRE(params);\n"
            + "\n"
            + "\tNOMBRE(params);\n"
            + "\n"
            + "\n"
            + "end";

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        lbl_arbol.setIcon(new ImageIcon("C:/Users/willi/OneDrive/Documentos/NetBeansProjects/Activaciones/src/main/java/Imagenes/wait.png"));
        txt_area.setText(PRUEBA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_crear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_arbol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        btn_crear.setText("ANALIZAR Y CREAR ARBOL");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(btn_crear, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_crear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ARBOL DE ACTIVACIONES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_arbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_arbol, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        if (txt_area.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa algo de texto primero");
        } else {
            String texto = txt_area.getText();
            parser par = new parser(new Lexer(new StringReader(texto)));
            try {
                par.parse();
                Programa p = par.pro;
                List<Instruccion> ins = p.getPrincipal();
                List<Metodo> met = p.getMetodos();
                operar(ins, met);

            } catch (Exception ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_crearActionPerformed

    public void operar(List<Instruccion> ins, List<Metodo> met) {
        for (int i = 0; i < ins.size(); i++) {
            System.out.println(ins.get(i).getTipo());
            if (ins.get(i).getTipo().equalsIgnoreCase("asignacion-metodo")) {
                if (!ins.get(i).getHeredadas().isEmpty()) {
                    Llamada ll = (Llamada) ins.get(i).getHeredadas().get(0);
                    System.out.println("llama al metodo " + ll.getId());
                    int existe = -1;
                    for (int j = 0; j < met.size(); j++) {
                        if (met.get(j).id.equalsIgnoreCase(ll.getId())) {
                            existe = j;
                            break;
                        }
                    }
                    if (existe >= 0) {
                        List<Instruccion> mets = met.get(existe).instrucciones;
                        operar(mets, met);
                    }
                }
            } else if (ins.get(i).getTipo().equalsIgnoreCase("llamada")) {
                Llamada ll = (Llamada) ins.get(i);
                System.out.println("llama al metodo " + ll.getId());
                int existe = -1;
                for (int j = 0; j < met.size(); j++) {
                    if (met.get(j).id.equalsIgnoreCase(ll.getId())) {
                        existe = j;
                        break;
                    }
                }
                if (existe >= 0) {
                    List<Instruccion> mets = met.get(existe).instrucciones;
                    operar(mets, met);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_arbol;
    private javax.swing.JTextArea txt_area;
    // End of variables declaration//GEN-END:variables
}
